### ISSUE TITLE
Webhook is using the wrong CA bundle in EKS 1.13

### ISSUE THREAD

**Issue by nckturner** [aws/aws-app-mesh-inject#63] opened 2019-07-11 01:28 UTC
Because the webhook generates a serving certificate using a Kubernetes CSR, it gets a serving certificate signed by the cluster CA.  [Due to the logic here](https://github.com/aws/aws-app-mesh-inject/blob/master/scripts/ca-bundle.sh#L8-L14), in 1.13 clusters we end up using the client CA from the extension-apiserver-authentication config-map (client-ca-file). 

Due to client CA auth being disabled for users in EKS clusters, this certificate is not the cluster CA.  We should remove https://github.com/aws/aws-app-mesh-inject/blob/master/scripts/ca-bundle.sh#L8-L10 and validate it works on 1.13 clusters.

**Comment by CarmenAPuccio** [comment] 2019-07-22 17:34
@geremyCohen and @nckturner I can confirm this work on EKS 1.13 but it took 2 changes. 

The instructions for the [aws-app-mesh-controller-for-ks8](https://github.com/aws/aws-app-mesh-controller-for-k8s/blob/master/docs/install.md) has the users run:
```
curl https://raw.githubusercontent.com/aws/aws-app-mesh-inject/v0.1.5/scripts/install.sh | bash
```

The instructions for [aws-app-mesh-inject](https://raw.githubusercontent.com/aws/aws-app-mesh-inject/master/scripts/install.sh) has the users run:
```
curl https://raw.githubusercontent.com/aws/aws-app-mesh-inject/master/scripts/install.sh | bash
```
Neither work work on EKS v1.13 because it uses v0.1.5 of [inject.yaml.template](https://raw.githubusercontent.com/aws/aws-app-mesh-inject/v0.1.5/deploy/inject.yaml.template) which doesn't have the ENABLE_STATSD fix from #56 which was merged into master. 

It also references v0.1.5 of [ca-bundle.sh](https://raw.githubusercontent.com/aws/aws-app-mesh-inject/v0.1.5/scripts/ca-bundle.sh) which doesn't have the fix addressed with this issue.

I'm not sure if you want to target the master branch in the scripts or create a new version and update accordingly. 

Also, the [AWS User Guide](https://docs.aws.amazon.com/app-mesh/latest/userguide/mesh-k8s-integration.html) has the users run v0.1.4 of the script which doesn't work on EKS v1.13 either.

**Comment by geremyCohen** [comment] 2019-07-23 05:13
Checking it out...

**Comment by geremyCohen** [comment] 2019-07-23 19:49
PRs filed:

https://github.com/aws/aws-app-mesh-controller-for-k8s/pull/51
https://github.com/awsdocs/aws-app-mesh-user-guide/pull/7
https://github.com/aws/aws-app-mesh-inject/pull/66

**Closed by geremyCohen** 2019-07-23 19:49 UTC
