### ISSUE TITLE
cannot install with EKS 1.16

### ISSUE THREAD

**Issue by RainaWLK** [aws/aws-app-mesh-inject#132] opened 2020-05-21 07:04 UTC
Hi:

Since EKS upgraded to 1.16, when I tried to install app mesh injector.

got

.......
error: unable to recognize "_output/inject.yaml": no matches for kind "Deployment" in version "apps/v1beta1"
Error from server (NotFound): deployments.apps "appmesh-inject" not found

It's because apps/v1beta1 is not supported in k8s 1.16. 

I also tried to edit inject.yaml.template, modify apps/v1beta1 to apps/v1. Then run "make deploy",

got

......
service/appmesh-inject unchanged
error: error validating "_output/inject.yaml": error validating data: ValidationError(Deployment.spec): missing required field "selector" in io.k8s.api.apps.v1.DeploymentSpec; if you choose to ignore these errors, turn validation off with --validate=false
make: *** [deploy] Error 1

please help, thank you

**Comment by zhiyanliu** [comment] 2020-05-26 06:32
Thanks for report this issue.

I can reproduce this issue on my environment. The root cause is current templates are still using apps/v1beta1 API version for the deployment resource. I will push a quick fix on this.

**Comment by zhiyanliu** [comment] 2020-05-26 06:35
Seems another PR already there to cover this, will review it instead

**Comment by M00nF1sh** [comment] 2020-05-27 20:13
@zhiyanliu  @RainaWLK 
Hi, you may want to try out our GA candidate: https://github.com/aws/eks-charts/tree/master/stable/appmesh-manager. It have backwards-incompatible changes to API types.

You can currently install it by below instructions. (you need to first uninstall old appmesh objects and crds and controller/injector)
```
git clone https://github.com/aws/eks-charts/tree/master/stable/appmesh-manager
kubectl apply -k github.com/aws/eks-charts/stable/appmesh-manager//crds?ref=master
helm upgrade -i appmesh-manager ./eks-charts/stable/appmesh-manager/ --namespace appmesh-system
```

**Comment by zhiyanliu** [comment] 2020-05-28 14:38
Hi @M00nF1sh ,

Thanks for the information, [0] is good. And CRD resources have been aligned as well, cool.

[0] https://github.com/aws/eks-charts/blob/master/stable/appmesh-manager/templates/deployment.yaml#L1

**Comment by RainaWLK** [comment] 2020-06-02 07:37
Hi @M00nF1sh ,

Thanks for your reply. But I'm confused what difference between appmesh-manager and others.

https://docs.aws.amazon.com/app-mesh/latest/userguide/mesh-k8s-integration.html
Here introduce how to install appmesh-controller and appmesh-inject using helm chart.

It means appmesh-manager is a fully integrated package which all parts of appmesh included, right?

**Comment by M00nF1sh** [comment] 2020-06-02 20:20
yes :D. and it's backwards-incompatible for old versions, so we decided to pick another name

**Comment by achevuru** [comment] 2020-06-18 18:53
Fixed in GA version.

**Closed by achevuru** 2020-06-18 18:53 UTC
